artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_file: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
  targer_column: quality

model_trainer:
  root_dir: artifacts/model_trainer
  X_data_path: artifacts/data_transformation/X.csv
  y_data_path: artifacts/data_transformation/y.csv
  model_name: best_model.pkl
  terget_column: quality


model_evaluation:
  root_dir: artifacts/model_evaluation
  X_test: artifacts/data_transformation/X_test.csv
  y_test: artifacts/data_transformation/y_test.csv
  model_path: artifacts/model_trainer/
  model_name: best_model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json
